const constant = {
  GET_DIRECTORY_PATH: 'GET_DIRECTORY_PATH',
  SEND_DIRECTORY_PATH: 'SEND_DIRECTORY_PATH',
  GET_APP_PATH: 'GET_APP_PATH',
  SEND_APP_PATH: 'SEND_APP_PATH',
  OPEN_VIDEO_DOWNLOAD_FOLDER: 'OPEN_VIDEO_DOWNLOAD_FOLDER',
};

export default constant;
